---
title: "C6318 | Microsoft Docs"
ms.custom: ""
ms.date: "11/04/2016"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "vs-devops-test"
ms.tgt_pltfrm: ""
ms.topic: "article"
f1_keywords: 
  - "C6318"
helpviewer_keywords: 
  - "C6318"
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
caps.latest.revision: 13
author: "corob-msft"
ms.author: "corob"
manager: "ghogen"
caps.handback.revision: 13
---
# C6318
[!INCLUDE[vs2017banner](../code-quality/includes/vs2017banner.md)]

警告 C6318: 定義錯誤的 \_\_try\/\_\_except: 在例外狀況篩選條件運算式中使用常數 EXCEPTION\_CONTINUE\_SEARCH 或其他評估為零的常數。  未執行例外狀況處理常式區塊中的程式碼  
  
 這則警告指出如果在此結構化例外處理常式的保護區塊中發生例外狀況，將不會處理此例外狀況，原因在於例外狀況篩選條件運算式中已使用常數 `EXCECPTION_CONTINUE_SEARCH`。  
  
 因為不會執行處理常式區塊，所以此程式碼相當於不含例外狀況處理常式區塊的保護區塊。  
  
## 範例  
 下列程式碼將產生出這個警告：  
  
```  
#include <excpt.h>  
#include <stdio.h>  
  
void f (char *pch)  
{  
  __try   
  {  
    // assignment might fail  
    *pch = 0;  
  }   
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318  
  {  
    puts("Exception Occurred");  
  }  
}  
```  
  
 若要更正這則警告，請使用下列程式碼：  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *pch)  
{  
  __try   
  {  
    // assignment might fail  
    *pch = 0;  
  }   
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?  
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )  
  {  
    puts("Access violation");  
  }  
}   
```  
  
## 請參閱  
 [try\-except 陳述式](/visual-cpp/cpp/try-except-statement)